[package]
name = "rust_modbus_client"
version = "0.1.0"
edition = "2022"
authors = ["Kelvin César de Andrade"]

[dependencies]
rmodbus = "0.6.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

